### ISSUE TITLE
Refs assigned to effects are always undefined

### ISSUE THREAD

**Issue by talentlessguy** [react-spring/react-postprocessing#1]
# The problem

At the moment of `1.0.0-beta3` if you try to pass a ref to an effect it will become `undefined`. 

It happens because `ref` prop is already occupied in `EffectComposer`:

https://github.com/react-spring/react-postprocessing/blob/3a89610a586326e5b78d7fb325053efd49326788/src/EffectComposer.tsx#L70

# Solution

One of the solutions is trying to merge refs. However, React drops an error about inproper usage of refs.

```
Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
```

I think the right one is making a custom prop `innerRef`. Last time I tried it, everything that used refs got broken  because of `composer` becoming `null` so I don't know yet what's the proper way of doing things here.

**Comment by drcmda** [comment]
What's reacts error when you merge? I use mergerefs all the time and never saw a warning, must be something else imo

**Comment by talentlessguy** [comment]
@drcmda here is the error I get:

```
Warning: [object Object]: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop.
```

it happens when I try to merge `refs[i]` and `el.props.ref`

here's a demo of this case: https://codesandbox.io/s/trying-to-get-effect-ref-9zzl1?file=/src/App.js

**Comment by drcmda** [comment]
try clone in that case https://reactjs.org/docs/react-api.html#cloneelement

> Clone and return a new React element using element as the starting point. The resulting element will have the original element’s props with the new props merged in shallowly. New children will replace existing children. key and ref from the original element will be preserved.

**Comment by talentlessguy** [comment]
@drcmda maybe I'm using this wrong but it's still `{ current: undefined }` :/

I used this [SO answer](https://stackoverflow.com/a/48644745/11889402) so the code looks like this:

```jsx
React.Children.map(children, (el: JSX.Element, i) => {
   return cloneElement(el, { ref: refs[i] })
})
```

and in demo it looks like this:

https://github.com/react-spring/react-postprocessing/blob/3a89610a586326e5b78d7fb325053efd49326788/examples/pages/outline.jsx#L10-L40

Even if it is said that `cloneElement` preserves refs, looks like here it gets overidden anyway.

**Comment by talentlessguy** [comment]
I've set up a codesandbox to debug the composer easier, but still no result yet :/

https://codesandbox.io/s/boring-noether-7uli0?file=/src/components/EffectComposer.tsx

it's being undefined

**Comment by talentlessguy** [comment]
@drcmda so I talked to some guys in a React chat and came to a conclusion that the whole `EffectComposer` implementation is wrong. We cannot merge refs, neither we can't assign them because they are occupied already.

I think that it's worth trying to implement it with children again, but there is a problem with state....

any ideas?

should I keep the existing implementation and keep trying to make it work (but I honestly don't know what else to try)

or it's better to completely rewrite the composer and effects?

**Comment by talentlessguy** [comment]
I think I got something: https://codesandbox.io/s/intelligent-dhawan-yo4lj?file=/src/App.tsx

might be some unexpected problems though

**Comment by talentlessguy** [comment]
Fixed in last version, works nicely!
