### ISSUE TITLE
<Effects Composer /> causes flashes when forwarded Context changes

### ISSUE THREAD

**Issue by stephencorwin** [react-spring/react-postprocessing#17]
I noticed an issue on my game that whenever I update the forwarded context value via `setState`, I would get a flash of blue like a bump map.

![effect-composer](https://user-images.githubusercontent.com/3931162/89324504-60a1c480-d655-11ea-97d8-1b4e706a9128.gif)

I abstracted the problem to a codesandbox:
https://codesandbox.io/s/nostalgic-pine-5f1jm?file=/src/App.js

I'm looking into it myself, but I figured I would post the issue here in case someone else has a chance to solve it before me.
I feel like the issue has something to do with the memoization on [Effect Composer](https://github.com/react-spring/react-postprocessing/blob/fb469ed02f0b9cef526f55484dbfad07188e1d7d/src/EffectComposer.tsx#L46). For example, the `useMemo` here doesn't actually do anything since it still creates a new object every time its [dependents change](https://github.com/react-spring/react-postprocessing/blob/fb469ed02f0b9cef526f55484dbfad07188e1d7d/src/EffectComposer.tsx#L21).

**Comment by drcmda** [comment]
i think `children` didnt belong in there - i released a patch

**Comment by stephencorwin** [comment]
@drcmda That fixed it.

Side note, it looks like we need to update the eslint configuration since it isn't picking up the hooks exhaustive dependencies.
```diff
"extends": [
    "plugin:@typescript-eslint/recommended",
    "eslint:recommended",
    "plugin:react/recommended",
+    "plugin:react-hooks/recommended",
    "prettier/@typescript-eslint",
    "prettier/react"
  ],
```

![exhaustive-deps](https://user-images.githubusercontent.com/3931162/89328926-1a039880-d65c-11ea-857c-ac2e8bce73f0.gif)

I'll commit this change shortly
