### ISSUE TITLE
Add Outline and SelectiveBloom

### ISSUE THREAD

**Issue by gsimone** [react-spring/react-postprocessing#22]
These are currently in but not working. I already started the work, posting this as a reminder

**Comment by jakubrpawlowski** [comment]
Outline kind of works but props don't seem to do anything. Tried changing strength, color, etc and they have no effect.
![image](https://user-images.githubusercontent.com/16911155/90585597-19095580-e18a-11ea-8ff6-ce177a67bda3.png)

**Comment by gsimone** [comment]
Closed by #24 #35
