### ISSUE TITLE
Resizing viewport causes weird glitching

### ISSUE THREAD

**Issue by jakubrpawlowski** [react-spring/react-postprocessing#32]
It happens even when effect composer component has no passes in it.

![ezgif-6-1b408dd04bc7](https://user-images.githubusercontent.com/16911155/90733190-10e01180-e281-11ea-8e4f-ba8384d34f0c.gif)

**Comment by drcmda** [comment]
could you `npx codesandbox .` your repo?

**Comment by stephencorwin** [comment]
fixed in 1.2.0 by https://github.com/react-spring/react-postprocessing/pull/38
