### ISSUE TITLE
Any way to use this without concurrent mode?

### ISSUE THREAD

**Issue by JackCA** [react-spring/react-postprocessing#6]
I have the capability to dynamically import modules in my react app, but would like to avoid adding an experimental mode to it.

Is there any way to use this without using `<Suspense>` -- I'm just looking for a tight integration with react-three-fiber and the dynamic loading is something I can handle using a different strategy.

**Comment by talentlessguy** [comment]
@JackCA hi, I'm not sure how it can be used without `<Suspense>` because the composer uses `useLoader` hook which requires suspense loading

**Comment by JackCA** [comment]
@talentlessguy gotcha, that makes sense. I'll continue to use `postprocessing` directly with the [hijacking method](https://github.com/react-spring/react-three-fiber/blob/master/recipes.md#dealing-with-effects-hijacking-main-render-loop).

**Comment by talentlessguy** [comment]
@JackCA can I close this issue?

**Comment by JackCA** [comment]
Yep, sounds good. Thanks for taking the time to follow up and help.
